version: 2

sources:
  - name: jaffle_shop
    description: A clone of a Postgres application database.
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        identifier: customers
        description: Raw customers data. One record per customer.
        columns:
          - name: id
            description: Primary key for raw customers.
            tests:
              - unique
              - not_null
      - name: orders
        identifier: orders
        description: Raw orders data. One record per order. Includes cancelled and deleted orders.
        columns:
          - name: id
            description: Primary key for raw orders.
            tests:
              - unique              
              - not_null
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

  - name: stripe
    description: unknown yet
    database: raw
    schema: stripe
    tables:
      - name: payment
        identifier: payment
        description: One record per payment.
        columns:
          - name: id
            description: Primary key for raw payments.
            tests:
              - unique              
              - not_null
        loaded_at_field: _batched_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
